os: linux
dist: xenial
language: shell
services: docker

env:
 jobs:
 - TOOLCHAIN=clang
   PACKAGES="clang-8 libc++-8-dev libc++abi-8-dev"
 - TOOLCHAIN=gcc
   PACKAGES="g++-8"

script:
- IMAGE=docker.pkg.github.com/bit2shift/r3v-toolchain/r3v-toolchain:$TRAVIS_BRANCH...$TOOLCHAIN
- docker build -t $IMAGE --build-arg PACKAGES .

before_deploy:
- docker login docker.pkg.github.com -u bot2shift --password-stdin <<<"$GITHUB_TOKEN"

deploy:
 provider: script
 script: docker push $IMAGE
 on:
  branch: gh-registry
