dist: xenial
services: docker
language: minimal

env:
- TOOLCHAIN=clang
  PACKAGES="clang-8 libc++-8-dev libc++abi-8-dev"
- TOOLCHAIN=gcc
  PACKAGES="g++-8"

before_script:
- IMAGE=r3v-toolchain-$TOOLCHAIN:$TRAVIS_BRANCH
- CNTNR=r3v-toolchain-$TOOLCHAIN-$TRAVIS_BRANCH

script:
- docker build -t $IMAGE --build-arg PACKAGES .
- docker create --name $CNTNR $IMAGE
- docker export $CNTNR | xz -9e >$CNTNR.txz &
- while kill -ALRM $! 2>/dev/null; do sleep 10; done; wait $!

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file: $CNTNR.txz
 skip_cleanup: true
 on:
  tags: true
