os: linux
dist: xenial
language: shell
services: docker

env:
- TOOLCHAIN=clang
- TOOLCHAIN=gcc

script:
- IMAGE="docker.pkg.github.com/bit2shift/r3v-toolchain/r3v-toolchain:$TRAVIS_BRANCH...$TOOLCHAIN"
- docker build -t "$IMAGE" --build-arg TOOLCHAIN .

before_deploy:
- docker login docker.pkg.github.com -u bot2shift --password-stdin <<< "$GITHUB_TOKEN"

deploy:
 provider: script
 script: docker push "$IMAGE"
 on:
  tags: true
