name: '[test] build some docker image'
on:
  workflow_dispatch:
jobs:
  docker-build:
    name: build image
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v2
    - name: derp
      run: find $PWD
