name: Build then publish Docker image
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - clang
          - gcc
    env:
      REGISTRY: ghcr.io
      IMAGE: ${{github.repository}}
      TOOLCHAIN: ${{matrix.toolchain}}
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          set -ex
          echo "URI: $REGISTRY/$IMAGE"
          echo docker build "--tag=$IMAGE:"{,"$GITHUB_REF_NAME-"}"$TOOLCHAIN" --build-arg=TOOLCHAIN .
